# Generated by Django 5.2.4 on 2025-07-29 06:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('meeting_type', models.CharField(choices=[('client', 'Client'), ('amc', 'AMC'), ('internal', 'Internal')], default='client', max_length=20)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('meeting_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
