# Generated by Django 5.2.4 on 2025-07-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_manager_conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='meeting_files/'),
        ),
    ]
