# Generated by Django 5.2.4 on 2025-07-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_manager_conversations', '0003_meeting_audio_file_alter_meeting_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio_files/'),
        ),
    ]
