# Generated by Django 5.2.4 on 2025-07-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_manager_conversations', '0004_alter_meeting_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='meeting_audio/'),
        ),
    ]
